- hosts: server
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Docker Master
      apt:
        name:
          - docker
          - docker-compose
        state: present
    - name: Login DockerHub
      shell: docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
    - name: Copy file
      copy:
        src: docker-compose-master.yml
        dest: /home/ubuntu/
    - name: Restart docker-compose master
      shell: |
          docker-compose -f docker-compose-master.yml stop
          docker-compose rm -f
          docker-compose -f docker-compose-master.yml pull
          docker-compose -f docker-compose-master.yml up -d
